[package]
name = "vulkanoing"
version = "0.1.0"
authors = ["guy <guy123levinger@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = "0.14.0"
vulkano-shaders = "0.14.0"
vulkano-win = "0.15.0"
winit = "0.20.0-alpha3"
lazy_static= "1.4"
#vulkano = "0.13"
#vulkano-shaders = "0.13"
#vulkano-win = "0.13"
#winit = "0.19"
